// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIMcwTYCL2J9VkE-MnuwEQuuzn3d-Ys10',
    appId: '1:291477367503:web:11da840f99683f936365ba',
    messagingSenderId: '291477367503',
    projectId: 'exercise6-c8a15',
    authDomain: 'exercise6-c8a15.firebaseapp.com',
    storageBucket: 'exercise6-c8a15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfRj6hD_nIVwtejdt0cQsbbpEsy8nJbW8',
    appId: '1:291477367503:android:e2117e6c0eff60296365ba',
    messagingSenderId: '291477367503',
    projectId: 'exercise6-c8a15',
    storageBucket: 'exercise6-c8a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_LgTC5joM23BwZ7QUzBLWdVU85TvwTkQ',
    appId: '1:291477367503:ios:e2c54b83fcadf8846365ba',
    messagingSenderId: '291477367503',
    projectId: 'exercise6-c8a15',
    storageBucket: 'exercise6-c8a15.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_LgTC5joM23BwZ7QUzBLWdVU85TvwTkQ',
    appId: '1:291477367503:ios:e2c54b83fcadf8846365ba',
    messagingSenderId: '291477367503',
    projectId: 'exercise6-c8a15',
    storageBucket: 'exercise6-c8a15.firebasestorage.app',
    iosBundleId: 'com.example.exercise6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIMcwTYCL2J9VkE-MnuwEQuuzn3d-Ys10',
    appId: '1:291477367503:web:209610e2e541b08e6365ba',
    messagingSenderId: '291477367503',
    projectId: 'exercise6-c8a15',
    authDomain: 'exercise6-c8a15.firebaseapp.com',
    storageBucket: 'exercise6-c8a15.firebasestorage.app',
  );
}
