// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCungZ1CSMBZ093mDNyANdhsPLYKVPirKw',
    appId: '1:261873933675:web:586f6d04b7b4264f28402e',
    messagingSenderId: '261873933675',
    projectId: 'exercise5a-164d7',
    authDomain: 'exercise5a-164d7.firebaseapp.com',
    storageBucket: 'exercise5a-164d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5koo4hyWEVdCtZmKFJyydM1asCX5r9Y',
    appId: '1:261873933675:android:44f8509a8c3fd77e28402e',
    messagingSenderId: '261873933675',
    projectId: 'exercise5a-164d7',
    storageBucket: 'exercise5a-164d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqQjACGs9WoYqa920aX-fjbeFW0RSAxBM',
    appId: '1:261873933675:ios:e0c031cc88986bb728402e',
    messagingSenderId: '261873933675',
    projectId: 'exercise5a-164d7',
    storageBucket: 'exercise5a-164d7.firebasestorage.app',
    iosClientId: '261873933675-s2jca1btg9pkr32god8fb7ntk6irhnsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqQjACGs9WoYqa920aX-fjbeFW0RSAxBM',
    appId: '1:261873933675:ios:e0c031cc88986bb728402e',
    messagingSenderId: '261873933675',
    projectId: 'exercise5a-164d7',
    storageBucket: 'exercise5a-164d7.firebasestorage.app',
    iosClientId: '261873933675-s2jca1btg9pkr32god8fb7ntk6irhnsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCungZ1CSMBZ093mDNyANdhsPLYKVPirKw',
    appId: '1:261873933675:web:d82eb1f5ebe6db4628402e',
    messagingSenderId: '261873933675',
    projectId: 'exercise5a-164d7',
    authDomain: 'exercise5a-164d7.firebaseapp.com',
    storageBucket: 'exercise5a-164d7.firebasestorage.app',
  );
}
